name: "Build with Ref Saved"
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Save base ref info
        run: |
          BASE="${{ github.base_ref }}"
          CURRENT_BRANCH="${{ github.head_ref }}"
          echo $BASE > base.txt
          echo $CURRENT_BRANCH > current-branch.txt
          cat base.txt
          cat current-branch.txt
      - name: Upload base ref info
        uses: actions/upload-artifact@v3
        with:
          name: original-refs
          path: |
            base.txt
            current-branch.txt
          retention-days: 1
