name: "Deploy After Merged"
on:
  workflow_run:
    workflows: ["Trigger Deploy Condition"]
    types: [completed]

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download a single artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          name: original-refs
          workflow_conclusion: success
      - name: set REF_BASE to env
        run: |
          {
            echo "BASE=$(cat base.txt)"
            echo "CURRENT_BRANCH=$(cat current-branch.txt)"
            echo "GITHUB_SHA_SHORTEN=$(cat github-sha.txt)"
          } >> $GITHUB_ENV
      - name: echo env
        run: echo "${{ toJSON(env) }}"
      - name: echo github.event.workflow_run
        run: echo "${{ toJSON(github.event.workflow_run) }}"
  # dump:
  #   runs-on: ubuntu-latest
  #   steps:
  #     -
  #       name: Dump context
  #       uses: crazy-max/ghaction-dump-context@v2
