name: "Link action"
on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - run: |
        echo The PR was merged
